### ISSUE TITLE
pedigree-viewer not found

### ISSUE THREAD

**Issue by nigelhorne** [stuporglue/TreeTrumpet#15]
Where is "pedigree-viewer.zip"?

"Unzip pedigree-viewer.zip and upload everything inside up to your server. That's all there is to the install. "

**Comment by stuporglue** [comment]
Sorry Nigel, 

TreeTrumpet was once upon a time forked from [Pedigree-Viewer](https://github.com/dovy/Pedigree-Viewer) and the README file never got updated. It should've said treetrumpet.zip.

Pedigree-Viewer was just the html5 tree/pedigree view component you see on the tree tab. 

I've updated the README on the site. 

Thanks,
Michael
